name: Markdown Link Check with errors

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Once a week: "At 00:00 on Sunday."

defaults:
  run:
    shell: pwsh

jobs:
  main:
    name: Run Markdown Link Check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Dump github context for debug purposes
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: $env:GITHUB_CONTEXT
    - uses: actions/checkout@v3
    - name: Markdown Link Check
      continue-on-error: true
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: .github/markdown-link-check-config.json
        folder-path: .github/workflows/markdown-link-check-files/with-errors/
        use-quiet-mode: no
    - name: Test something
      run: |
        $value = '${{ github.job == 'wtf' && format('{0}', 'wtf') || '--json-filepath' }}'
        Write-Output $value

        $value2 = '${{ github.job == 'main' && format('{0}', 'main') || '--json-filepath' }}'
        Write-Output $value2

        $value3 = '${{ github.job == 'main' && format('{0}', '') || '--json-filepath' }}'
        Write-Output $value3

        $value4 = '${{ github.job == 'main' && ' ' || '--json-filepath' }}'
        Write-Output $value4
